seed = 0
parent_dir = "exp/diabetes/mlp"
real_data_path = "data/diabetes/"
num_numerical_features = 8
mlp_type='binary_classification'
mlp_checkpoint='epoch=499-step=15500.ckpt'
device = "cuda:0"

[model_params]
d_in = 8
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    4,
    4,
    4,
    4,
]
dropout = 0.0

[train.main]
epochs = 500
lr = 0.000156
weight_decay = 0.00001
batch_size = 16

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
